In [17]:
from sklearn.datasets import load_diabetes

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
import random

In [18]:
X,y = load_diabetes(return_X_y=True)

In [19]:
X_train, X_test, y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=2)

In [20]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [21]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [22]:
lr.intercept_

151.88331005254167

In [23]:
y_pred = lr.predict(X_test)

In [24]:
r2_score(y_test,y_pred)

0.4399338661568969

In [31]:
class MBGDRegressor :

    def __init__(self, lrate=0.1, epochs = 100, batch_size=10):
        self.lrate = lrate
        self.epochs = epochs
        self.batch_size = batch_size
        self.intercept_ = None
        self.coef_ = None

    def fit(self,X_train,y_train):
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])

        for i in range(self.epochs):

            for j in range(X_train.shape[0]//self.batch_size):

                idx = random.sample(range(X_train.shape[0]),self.batch_size)

                y_hat = self.intercept_ + np.dot(X_train[idx], self.coef_)
                i_der = -2 * np.mean((y_train[idx] - y_hat))
                self.intercept_ = self.intercept_ - (self.lrate * i_der)


                c_der = -2 *(np.dot((y_train[idx]-y_hat),X_train[idx]))
                self.coef_  = self.coef_ - (self.lrate * c_der)

        print(self.intercept_)
        print(self.coef_)

    def predict(self,X_test):
        return self.intercept_ + np.dot(X_test,self.coef_)

In [32]:
mbgd = MBGDRegressor(lrate=0.01,epochs=70)
mbgd.fit(X_train, y_train)

149.58346980350362
[  44.99873149 -103.45954421  385.15588897  283.93923984    3.80632359
  -53.73218948 -182.66528045  126.11197966  361.73983403  122.29311185]


In [33]:
y_pred = mbgd.predict(X_test)

In [34]:
r2_score(y_test,y_pred)

0.44318950094430987

In [36]:
from sklearn.linear_model import SGDRegressor

In [37]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.1)
batch_size = 35

In [42]:
for i in range(100):
    idx = random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[idx],y_train[idx])


In [43]:
sgd.coef_

array([  72.5108806 ,  -53.28246518,  348.83224633,  257.84417825,
         13.75576348,  -28.97888627, -162.22448992,  116.92780742,
        301.70454647,  144.09521656])

In [44]:
sgd.intercept_

array([144.77822531])

In [45]:
y_pred = sgd.predict(X_test)
r2_score(y_test,y_pred)

0.41757497734397997