In [1]:
from sklearn.datasets import load_breast_cancer

In [4]:
cancer = load_breast_cancer()

In [6]:
cancer.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [9]:
import pandas as pd
import numpy as np

df = pd.DataFrame(cancer['data'],columns=cancer['feature_names'])

In [10]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness   
0        17.99         10.38          122.80     1001.0          0.11840  \
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry   
0           0.27760          0.3001              0.14710         0.2419  \
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter   
0                 0.07871  ...         25.38          17.33           184.60  \
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity   
0      2019.0            0.1622             0.6656           0.7119  \
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [11]:
df.shape

(569, 30)

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
dfs=scaler.fit_transform(df)
dfs

In [15]:
y = cancer['target']

In [16]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [20]:
features = dfs.T
print(features)
cov_matrix = np.cov(features)

[[ 1.09706398  1.82982061  1.57988811 ...  0.70228425  1.83834103
  -1.80840125]
 [-2.07333501 -0.35363241  0.45618695 ...  2.0455738   2.33645719
   1.22179204]
 [ 1.26993369  1.68595471  1.56650313 ...  0.67267578  1.98252415
  -1.81438851]
 ...
 [ 2.29607613  1.0870843   1.95500035 ...  0.41406869  2.28998549
  -1.74506282]
 [ 2.75062224 -0.24388967  1.152255   ... -1.10454895  1.91908301
  -0.04813821]
 [ 1.93701461  0.28118999  0.20139121 ... -0.31840916  2.21963528
  -0.75120669]]


In [18]:
cov_matrix

array([[ 1.00176056e+00,  3.24351929e-01,  9.99612069e-01,
         9.89095475e-01,  1.70881506e-01,  5.07014640e-01,
         6.77955036e-01,  8.23976636e-01,  1.48001350e-01,
        -3.12179472e-01,  6.80285970e-01, -9.74887767e-02,
         6.75358538e-01,  7.37159198e-01, -2.22992026e-01,
         2.06362656e-01,  1.94545531e-01,  3.76831225e-01,
        -1.04504545e-01, -4.27163418e-02,  9.71245907e-01,
         2.97530545e-01,  9.66835698e-01,  9.42739295e-01,
         1.19826732e-01,  4.14190751e-01,  5.27839123e-01,
         7.45524434e-01,  1.64241985e-01,  7.07832563e-03],
       [ 3.24351929e-01,  1.00176056e+00,  3.30113223e-01,
         3.21650988e-01, -2.34296930e-02,  2.37118951e-01,
         3.02950254e-01,  2.93980713e-01,  7.15266864e-02,
        -7.65717560e-02,  2.76354360e-01,  3.87037830e-01,
         2.82169018e-01,  2.60302460e-01,  6.62542133e-03,
         1.92312595e-01,  1.43545353e-01,  1.64139495e-01,
         9.14323671e-03,  5.45533955e-02,  3.53193674e-

In [21]:
cov_matrix.shape

(30, 30)

In [23]:
values,vectors = np.linalg.eig(cov_matrix)
values

array([1.33049908e+01, 5.70137460e+00, 2.82291016e+00, 1.98412752e+00,
       1.65163324e+00, 1.20948224e+00, 6.76408882e-01, 4.77456255e-01,
       4.17628782e-01, 3.51310875e-01, 2.94433153e-01, 2.61621161e-01,
       2.41782421e-01, 1.57286149e-01, 9.43006956e-02, 8.00034045e-02,
       5.95036135e-02, 5.27114222e-02, 4.95647002e-02, 1.33279057e-04,
       7.50121413e-04, 1.59213600e-03, 6.91261258e-03, 8.19203712e-03,
       1.55085271e-02, 1.80867940e-02, 2.43836914e-02, 2.74877113e-02,
       3.12142606e-02, 3.00256631e-02])

In [24]:
vectors

array([[ 2.18902444e-01, -2.33857132e-01, -8.53124284e-03,
         4.14089623e-02, -3.77863538e-02,  1.87407904e-02,
         1.24088340e-01,  7.45229622e-03, -2.23109764e-01,
         9.54864432e-02,  4.14714866e-02,  5.10674568e-02,
         1.19672116e-02, -5.95061348e-02, -5.11187749e-02,
         1.50583883e-01, -2.02924255e-01, -1.46712338e-01,
        -2.25384659e-01, -7.02414091e-01,  2.11460455e-01,
        -2.11194013e-01, -1.31526670e-01,  1.29476396e-01,
         1.92264989e-02, -1.82579441e-01,  9.85526942e-02,
        -7.29289034e-02, -4.96986642e-02,  6.85700057e-02],
       [ 1.03724578e-01, -5.97060883e-02,  6.45499033e-02,
        -6.03050001e-01,  4.94688505e-02, -3.21788366e-02,
        -1.13995382e-02, -1.30674825e-01,  1.12699390e-01,
         2.40934066e-01, -3.02243402e-01,  2.54896423e-01,
         2.03461333e-01,  2.15600995e-02, -1.07922421e-01,
         1.57841960e-01,  3.87061187e-02,  4.11029851e-02,
        -2.97886446e-02, -2.73661018e-04, -1.05339342e-

In [27]:
percentage = []
for value in values:
    percentage.append((value/np.sum(values))*100)

In [28]:
percentage

[44.27202560752635,
 18.971182044033085,
 9.39316325743139,
 6.60213491547013,
 5.495768492346286,
 4.024522039883351,
 2.250733712982507,
 1.588723800021325,
 1.389649374559104,
 1.1689781894131481,
 0.979718987598014,
 0.8705379007378824,
 0.8045249871967314,
 0.5233657454926371,
 0.3137832167627384,
 0.26620933651523127,
 0.19799679253242683,
 0.17539594502263622,
 0.1649253059225167,
 0.0004434827427365342,
 0.0024960103246884765,
 0.005297792903809173,
 0.023001546250596232,
 0.027258799547749485,
 0.051604237916518796,
 0.06018335666716732,
 0.08113612588991063,
 0.09146467510543438,
 0.10386467483387046,
 0.0999096463700246]

In [31]:
d1 = np.dot(dfs,vectors.T[0])
d2 = np.dot(dfs,vectors.T[1],)
d3 = np.dot(dfs,vectors.T[2],)

In [32]:
result = pd.DataFrame(d1,columns=['PC1'])

In [33]:
result['PC2']=d2
result['PC3']=d3

In [34]:
result

PC1        PC2       PC3
0     9.192837   1.948583 -1.123166
1     2.387802  -3.768172 -0.529293
2     5.733896  -1.075174 -0.551748
3     7.122953  10.275589 -3.232790
4     3.935302  -1.948072  1.389767
..         ...        ...       ...
564   6.439315  -3.576817  2.459487
565   3.793382  -3.584048  2.088476
566   1.256179  -1.902297  0.562731
567  10.374794   1.672010 -1.877029
568  -5.475243  -0.670637  1.490443

[569 rows x 3 columns]

In [35]:
result['target']=y

In [36]:
result

PC1        PC2       PC3  target
0     9.192837   1.948583 -1.123166       0
1     2.387802  -3.768172 -0.529293       0
2     5.733896  -1.075174 -0.551748       0
3     7.122953  10.275589 -3.232790       0
4     3.935302  -1.948072  1.389767       0
..         ...        ...       ...     ...
564   6.439315  -3.576817  2.459487       0
565   3.793382  -3.584048  2.088476       0
566   1.256179  -1.902297  0.562731       0
567  10.374794   1.672010 -1.877029       0
568  -5.475243  -0.670637  1.490443       1

[569 rows x 4 columns]

In [44]:
import seaborn as sns
import matplotlib.pyplot as plt

In [52]:
plt.figure(figsize=(20,10))
sns.scatterplot(x=result['PC1'],y=result['PC2'],hue=result['target'])

<Axes: xlabel='PC1', ylabel='PC2'>

In [53]:
new = result.drop(columns=['target'],axis=1)

In [54]:
new

PC1        PC2       PC3
0     9.192837   1.948583 -1.123166
1     2.387802  -3.768172 -0.529293
2     5.733896  -1.075174 -0.551748
3     7.122953  10.275589 -3.232790
4     3.935302  -1.948072  1.389767
..         ...        ...       ...
564   6.439315  -3.576817  2.459487
565   3.793382  -3.584048  2.088476
566   1.256179  -1.902297  0.562731
567  10.374794   1.672010 -1.877029
568  -5.475243  -0.670637  1.490443

[569 rows x 3 columns]

In [55]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [56]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(new,y,test_size=0.33,random_state=42)

In [58]:
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

LogisticRegression()

In [60]:
x_train,x_test,y_train,y_test = train_test_split(dfs,y,test_size=0.33,random_state=42)

In [61]:
lr.fit(x_train,y_train)

LogisticRegression()

In [62]:
lr.score(x_test,y_test)

0.9787234042553191