In [24]:
import numpy as np
import pandas as pd

np.random.seed(23) 

mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

df = pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target'] = 1
df


feature1  feature2  feature3  target
0   0.666988  0.025813 -0.777619       1
1   0.948634  0.701672 -1.051082       1
2  -0.367548 -1.137460 -1.322148       1
3   1.772258 -0.347459  0.670140       1
4   0.322272  0.060343 -1.043450       1
5  -1.009942  0.441736  1.128877       1
6  -1.838068 -0.938769 -0.201841       1
7   1.045371  0.538162  0.812119       1
8   0.241106 -0.952510 -0.136267       1
9   1.267248  0.173634 -1.223255       1
10  1.415320  0.457711  0.728876       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1
13 -0.022539  0.013422  0.935945       1
14  0.420623  0.411620 -0.071324       1
15 -0.045438  1.040886 -0.094035       1
16 -0.420844 -0.551989 -0.121098       1
17  0.190141  0.512137  0.131538       1
18 -0.331617 -1.632386  0.619114       1
19 -0.992574 -0.161346  1.192404       1

In [25]:
mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

df1 = pd.DataFrame(class2_sample,columns=['feature1','feature2','feature3'])

df1['target'] = 0
df1

feature1  feature2  feature3  target
0   1.250737  0.186384  1.703624       0
1   0.731858  0.517441  2.244610       0
2   1.676860  4.187503 -0.080565       0
3   1.010229  1.437830  2.327788       0
4   0.748855  2.593111  1.170818       0
5   0.290746  0.866975  0.982643       0
6   0.898907  0.435960  0.820964       0
7   2.011059  1.920996  2.933090       0
8   0.204637 -0.011535  3.150780       0
9   1.425140  1.441152  0.182561       0
10  1.437892  1.099723  1.065406       0
11  2.224431  0.230401  1.192120       0
12 -0.723253  1.461259 -0.085367       0
13  2.823378 -0.332863  2.637391       0
14  0.177061 -0.598109  1.226512       0
15  1.233898  0.052778 -0.261576       0
16 -1.389866  0.666726  1.343517       0
17 -1.027861  1.131416  2.603234       0
18 -0.764314  1.566504  1.548788       0
19  0.384865  1.323546 -0.103193       0

In [26]:
df = pd.concat([df1,df],axis=0)

df = df.sample(40)
df

feature1  feature2  feature3  target
2   1.676860  4.187503 -0.080565       0
14  0.420623  0.411620 -0.071324       1
14  0.177061 -0.598109  1.226512       0
11  2.224431  0.230401  1.192120       0
12 -0.723253  1.461259 -0.085367       0
9   1.267248  0.173634 -1.223255       1
11  1.968435 -0.547788 -0.679418       1
4   0.748855  2.593111  1.170818       0
12 -2.506230  0.146960  0.606195       1
13 -0.022539  0.013422  0.935945       1
16 -0.420844 -0.551989 -0.121098       1
18 -0.764314  1.566504  1.548788       0
0   1.250737  0.186384  1.703624       0
5   0.290746  0.866975  0.982643       0
19 -0.992574 -0.161346  1.192404       1
2  -0.367548 -1.137460 -1.322148       1
8   0.204637 -0.011535  3.150780       0
15  1.233898  0.052778 -0.261576       0
19  0.384865  1.323546 -0.103193       0
10  1.415320  0.457711  0.728876       1
5  -1.009942  0.441736  1.128877       1
1   0.948634  0.701672 -1.051082       1
17  0.190141  0.512137  0.131538       1
16 -1.389866  0.666726  1.343517       0
18 -0.331617 -1.632386  0.619114       1
7   1.045371  0.538162  0.812119       1
6  -1.838068 -0.938769 -0.201841       1
3   1.772258 -0.347459  0.670140       1
1   0.731858  0.517441  2.244610       0
10  1.437892  1.099723  1.065406       0
0   0.666988  0.025813 -0.777619       1
8   0.241106 -0.952510 -0.136267       1
4   0.322272  0.060343 -1.043450       1
7   2.011059  1.920996  2.933090       0
6   0.898907  0.435960  0.820964       0
17 -1.027861  1.131416  2.603234       0
13  2.823378 -0.332863  2.637391       0
9   1.425140  1.441152  0.182561       0
15 -0.045438  1.040886 -0.094035       1
3   1.010229  1.437830  2.327788       0

In [27]:
import plotly.express as px
#y_train_trf = y_train.astype(str)
fig = px.scatter_3d(df, x=df['feature1'], y=df['feature2'], z=df['feature3'],
              color=df['target'].astype('str'))
fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))

fig.show()

In [28]:
# Step 1 - Apply standard scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])

In [29]:
# Step 2 - Find Covariance Matrix
covariance_matrix = np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print('Covariance Matrix:\n', covariance_matrix)

Covariance Matrix:
 [[1.02564103 0.20478114 0.080118  ]
 [0.20478114 1.02564103 0.19838882]
 [0.080118   0.19838882 1.02564103]]


In [30]:
# Step 3 - Finding EV and EVs
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

In [31]:
eigen_values

array([1.3536065 , 0.94557084, 0.77774573])

In [32]:
eigen_vectors

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442],
       [-0.52848211,  0.72025103,  0.44938304]])

In [33]:
%pylab inline

from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d import proj3d
from matplotlib.patches import FancyArrowPatch


class Arrow3D(FancyArrowPatch):
    def __init__(self, xs, ys, zs, *args, **kwargs):
        FancyArrowPatch.__init__(self, (0,0), (0,0), *args, **kwargs)
        self._verts3d = xs, ys, zs

    def draw(self, renderer):
        xs3d, ys3d, zs3d = self._verts3d
        xs, ys, zs = proj3d.proj_transform(xs3d, ys3d, zs3d, renderer.M)
        self.set_positions((xs[0],ys[0]),(xs[1],ys[1]))
        FancyArrowPatch.draw(self, renderer)

fig = plt.figure(figsize=(7,7))
ax = fig.add_subplot(111, projection='3d')

ax.plot(df['feature1'], df['feature2'], df['feature3'], 'o', markersize=8, color='blue', alpha=0.2)
ax.plot([df['feature1'].mean()], [df['feature2'].mean()], [df['feature3'].mean()], 'o', markersize=10, color='red', alpha=0.5)
for v in eigen_vectors.T:
    a = Arrow3D([df['feature1'].mean(), v[0]], [df['feature2'].mean(), v[1]], [df['feature3'].mean(), v[2]], mutation_scale=20, lw=3, arrowstyle="-|>", color="r")
    ax.add_artist(a)
ax.set_xlabel('x_values')
ax.set_ylabel('y_values')
ax.set_zlabel('z_values')

plt.title('Eigenvectors')

plt.show()

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


AttributeError: 'Arrow3D' object has no attribute 'do_3d_projection'

<Figure size 700x700 with 1 Axes>

In [ ]:
pc = eigen_vectors[0:2]
pc
     

array([[ 0.25669313,  0.94218078, -0.21541592],
       [ 0.70266533, -0.02889354,  0.71093361]])

In [ ]:
transformed_df = np.dot(df.iloc[:,0:3],pc.T)
# 40,3 - 3,2
new_df = pd.DataFrame(transformed_df,columns=['PC1','PC2'])
new_df['target'] = df['target'].values
new_df.head()

PC1       PC2  target
0 -0.135187 -0.954182       0
1 -0.681884 -0.475598       1
2  0.106145  0.420846       1
3 -0.135187 -0.954182       0
4  0.883028  0.251788       0

In [34]:

import plotly.express as px
new_df['target'] = new_df['target'].astype('str')
fig = px.scatter(x=new_df['PC1'],
                 y=new_df['PC2'],
                 color=new_df['target'],
                 color_discrete_sequence=px.colors.qualitative.G10
                )

fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))
fig.show()